### ISSUE TITLE
Page not Found returned when trying to create custom webhook payload templates

### ISSUE THREAD

**Issue by Mesverrum** [meraki/webhook-payload-templates#5]
I've been chasing this since yesterday and no matter what method I used I always ended up with the same results.  I'm able to list  all the existing webhooks just fine, but when I try to post a new one I only get "page not found" responses.  I've tried using curl, postman, and the python script from this repo and all had the exact same results.  If I intentionally mangle my API key or network ID I get errors specific to those issues, and all read operations are working fine. The only thing I can think of that might be a limiting factor on my end is that I just created my Meraki account and haven't associated and hardware to it yet.   
Is there a limitation that you can't post a template until you have hardware or is there just something wrong with the POST endpoint over the last 24 hours?

**Comment by dexterlabora** [comment]
If you are still having issues, can you provide an example of the API/script or screenshot of your method and results?

Are you able to perform other "write" actions with the network you are doing this with?

There is no time limit delay for API/webhook usage. You just need to have an organization with API enabled, an account (email) with Read/write permissions to the org, and an API key.

Creating a template could have some funny syntax in it, so the more info you provide the easier it will be to spot the issue.
